server:
  port: 10010
  eureka:
    client:
      service-url:
        defaultZone: http://127.0.0.1:10086/eureka
spring:
  application:
    name: gateway
zuul:
  routes:
    user-service: /user/**
  strip-prefix: false
  ignored-services:
    - consumer-service
  prefix: /api #全局的前缀，使用全局strip-prefix去除前缀
hystrix: # hystrix 的超时时长
  commend:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillSeconds: 2000
ribbon: # ribbon的超时时长
  ConnectionTimeout: 500
  ReadTimeout: 4000